version: "3.8"

services:
  discordbot:
    image: ephaltes/discordbot
    container_name: discordbot
    restart: "unless-stopped"
    volumes:
      - ./data:/data
    environment:
      - AppSettingsPath=/data/appsettings.json